name: itrue-qt-imx-snap
base: core26
version: '5.6.3'
summary: Qt application libraries for i.MX 6 & 8 SoCs
description: |
  Qt application libraries compiled with support for the eglfs backend on i.MX
  6 & 8 SoCs.

  Users can either use this snap in `stage-snaps` to utilise the prebuilt
  libraries for their application, or extend this snap by adding the appropriate
  build steps.

  The Qt libraries are available in the /usr/local/qt5 directory in the snap.

  As part of the build process, the GPU library binaries for the SoCs are
  downloaded, extracted, and added to the snap. It's assumed you know what
  you're doing, license-wise, if you're using and/or distributing this snap.

grade: devel
confinement: devmode

platforms:
  arm64:
    build-on: [amd64]
    build-for: [arm64]

plugs:
  gpu:
    interface: custom-device

parts:
  imx-gpu-viv:
    plugin: dump
    source: .
    build-packages:
      - wget
    override-pull: |
      if [ "${CRAFT_TARGET_ARCH}" = "armhf" ]; then
        export WGET_ARCH="aarch32"
      elif [ "${CRAFT_TARGET_ARCH}" = "arm64" ]; then
        export WGET_ARCH="aarch64"
      else
        echo "not supported!"
        exit -1
      fi
      rm -f ${CRAFT_PART_SRC}/imx-gpu-viv.bin
      wget https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-gpu-viv-6.4.3.p0.0-${WGET_ARCH}.bin \
        -O ${CRAFT_PART_SRC}/imx-gpu-viv.bin
      chmod a+x ${CRAFT_PART_SRC}/imx-gpu-viv.bin
      ${CRAFT_PART_SRC}/imx-gpu-viv.bin --auto-accept --force
    organize:
      imx-gpu-viv-6.4.3.p0.0-aarch64/gpu-core/usr/lib/fb/*: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/
      imx-gpu-viv-6.4.3.p0.0-aarch64/gpu-core/usr/lib/*.so*: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/
      imx-gpu-viv-6.4.3.p0.0-aarch64/gpu-core/usr/lib/pkgconfig: usr/lib/pkgconfig
      imx-gpu-viv-6.4.3.p0.0-aarch64/gpu-core/usr/lib/dri: usr/lib/dri
      imx-gpu-viv-6.4.3.p0.0-aarch64/gpu-core/usr/include: usr/include
      imx-gpu-viv-6.4.3.p0.0-aarch64/gpu-core/etc/Vivante.icd: etc/OpenCL/vendors/Vivante.icd
    stage:
      - -imx-gpu-viv.bin
      - -imx-gpu-viv-6.4.3.p0.0-aarch64
      - -patches

  dependencies:
    plugin: nil
    stage-packages:
      # Qt needs a lot of packages from the target arch to build.
      # Normally these would go in build-packages but Qt does a lot of
      # cross-compilation for feature detection
      - libglvnd-dev
      - libdrm-dev
      - libicu-dev
      - libc-dev
      - libcrypt-dev
      - libssl-dev
      - libpcre2-dev
      - libdbus-1-dev
      - libts-dev
      - libinput-dev
      - libfontconfig-dev
      - libwayland-dev
      - libbsd0
      - libglvnd0
      - libdrm2
      - libicu78
      - libcrypt1
      - libdbus-1-3
      - libffi8
      - libglapi-mesa
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-server0
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxdamage1
      # Normally these shouldn't be in the snap, but Snapcraft complains about
      # dangling symlinks
      - libstdc++6
      - zlib1g
      - libexpat1
      - libgcc-s1
      - libc6
      - libblkid1
      - libpcre3
      - libuuid1
      - libselinux1
      - libsepol2
      - libmount1
    override-build: |
      craftctl default
      # Move all files from /lib to /usr/lib and create a symlink
      cp -r ${CRAFT_PART_INSTALL}/lib/* ${CRAFT_PART_INSTALL}/usr/lib/
      rm -rf ${CRAFT_PART_INSTALL}/lib
      ln -sr ${CRAFT_PART_INSTALL}/usr/lib ${CRAFT_PART_INSTALL}/lib
    stage:
      # Remove all mesa GL libraries
      - -usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libGLES*
      - -usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libGL.*
      - -usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libEGL*
      - -usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libGLX*
      - -usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libvulkan*
      - -usr/include/EGL
      - -usr/include/GL
      - -usr/include/GLES*
      - -usr/include/KHR/khrplatform.h
    prime:
      - -usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/dri
      - -usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libdrm_*
      - -usr/lib/udev
      - -usr/lib/cmake
      - -usr/share/doc

  qt5:
    after:
      - imx-gpu-viv
      - dependencies
    plugin: nil
    source: https://github.com/qt/qt5.git
    source-tag: v5.6.3
    source-depth: 1
    build-environment:
      - PATH: /usr/lib/ccache:${PATH}
      - on amd64:
        - DEVICE_OPTIONS: "-device-option CROSS_COMPILE=${CRAFT_ARCH_TRIPLET_BUILD_FOR}-"
        - to armhf:
          - DEVICE: "linux-imx6-g++"
        - to arm64:
          - DEVICE: "linux-imx8-g++"
      - on armhf:
        - DEVICE_OPTIONS: ""
        - DEVICE: "linux-imx6-g++"
      - on arm64:
        - DEVICE_OPTIONS: ""
        - DEVICE: "linux-imx8-g++"
    build-packages:
      - patch
      - pkg-config
      - python-is-python3
    override-pull: |
      craftctl default
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/0001-Added-linux-imx8-g.patch
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/0002-Do-not-enforce-CROSS_COMPILE.patch
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/0003-SocketCAN-Fix-compiler-error-SIOCGSTAMP-was-not-decl.patch
    override-build: |
      # Unset all snapcraft build variables so they don't interfere
      unset LD
      unset CC
      unset CXX
      unset CFLAGS
      unset CXXFLAGS
      unset LDFLAGS
      unset PKG_CONFIG_PATH

      ./configure -debug -nomake tests -nomake examples -opensource -confirm-license \
        -prefix /usr -sysroot ${CRAFT_STAGE} \
        -opengl es2 -no-pulseaudio -qpa eglfs -no-xcb -qt-pcre \
        -qt-libjpeg -qt-libpng -qt-freetype -qt-zlib \
        -pkg-config -no-mtdev \
        -xkb-config-root /snap/qt-imx/current/usr/share/X11/xkb \
        -device ${DEVICE} ${DEVICE_OPTIONS} \
        -no-alsa -no-openssl -no-audio-backend -no-use-gold-linker \
        -extprefix ${CRAFT_PART_INSTALL}/usr \
        -skip qtwebengine \
        -libdir ${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/

      make -j$(nproc)

      make install
    stage:
      - -lib
    prime:
      - -usr/doc

  qt-conf:
    after:
      - qt5
    plugin: nil
    override-build: |
      cat > ${CRAFT_PART_INSTALL}/qt.conf << EOF
      [Paths]
      Prefix = ../
      Libraries = ../lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/
      Sysroot = ../../
      EOF
    organize:
      qt.conf: usr/bin/qt.conf

  hello-world:
    after:
      - qt5
    plugin: nil
    source: hello-world
    stage-packages:
      - strace
      - gdb
    override-build: |
      ${CRAFT_STAGE}/usr/bin/qmake
      make -j$(nproc)
      make INSTALL_ROOT=${CRAFT_PART_INSTALL} install
    stage:
      - -lib

apps:
  hello-world:
    command: opt/hello-world/bin/hello-world
    environment:
      QT_PLUGIN_PATH: $SNAP/usr/plugins
    plugs:
      - opengl
      - hardware-observe
      - framebuffer
      - gpu

build-packages:
  - cmake
  - build-essential
  - perl
  - python3
  - ccache
  - on amd64:
    - g++-${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    - gcc-${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    - binutils-${CRAFT_ARCH_TRIPLET_BUILD_FOR}
  - else:
    - g++

layout:
  /etc/glvnd:
    bind: $SNAP/etc/glvnd
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/glvnd:
    bind: $SNAP/usr/share/glvnd
  /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/dri:
    bind: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/dri
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/lib/fonts:
    bind: $SNAP/usr/lib/fonts
